name: coffee_shop
description: "Coffe_Shop"
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  google_nav_bar: ^5.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf

    - family: Sallim
      fonts:
        - asset: assets/fonts/SallimSignature.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    
    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf


