class Coffee {
  Coffee({
    required this.name,
    required this.intensity,
    required this.beverageType,
    required this.price,
    required this.isAtive,
    required this.bestSellers,
  });
  final String name;
  final int intensity;
  final String beverageType;
  final double price;
  final bool isAtive;
  final bool bestSellers;
}

List<Coffee> coffees = [
  Coffee(
    name: 'Espresso 1',
    intensity: 5,
    beverageType: 'Espresso',
    price: 3.50,
    isAtive: true,
    bestSellers: true,
  ),
  Coffee(
    name: 'Espresso 2',
    intensity: 4,
    beverageType: 'Espresso',
    price: 4,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Espresso 3',
    intensity: 5,
    beverageType: 'Espresso',
    price: 3.75,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Espresso 4',
    intensity: 4,
    beverageType: 'Espresso',
    price: 3.90,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Espresso 5',
    intensity: 5,
    beverageType: 'Espresso',
    price: 4.25,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Cappuccino 1',
    intensity: 3,
    beverageType: 'Cappuccino',
    price: 5.50,
    isAtive: true,
    bestSellers: true,
  ),
  Coffee(
    name: 'Cappuccino 2',
    intensity: 4,
    beverageType: 'Cappuccino',
    price: 6,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Cappuccino 3',
    intensity: 3,
    beverageType: 'Cappuccino',
    price: 5.75,
    isAtive: true,
    bestSellers: true,
  ),
  Coffee(
    name: 'Cappuccino 4',
    intensity: 4,
    beverageType: 'Cappuccino',
    price: 6.20,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Cappuccino 5',
    intensity: 3,
    beverageType: 'Cappuccino',
    price: 5.90,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Latte 1',
    intensity: 3,
    beverageType: 'Latte',
    price: 6,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Latte 2',
    intensity: 3,
    beverageType: 'Latte',
    price: 6.25,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Latte 3',
    intensity: 2,
    beverageType: 'Latte',
    price: 5.75,
    isAtive: true,
    bestSellers: true,
  ),
  Coffee(
    name: 'Latte 4',
    intensity: 3,
    beverageType: 'Latte',
    price: 6.50,
    isAtive: true,
    bestSellers: true,
  ),
  Coffee(
    name: 'Latte 5',
    intensity: 3,
    beverageType: 'Latte',
    price: 6.30,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Macchiato 1',
    intensity: 4,
    beverageType: 'Macchiato',
    price: 4.50,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Macchiato 2',
    intensity: 3,
    beverageType: 'Macchiato',
    price: 4.75,
    isAtive: true,
    bestSellers: true,
  ),
  Coffee(
    name: 'Macchiato 3',
    intensity: 4,
    beverageType: 'Macchiato',
    price: 4.60,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Macchiato 4',
    intensity: 3,
    beverageType: 'Macchiato',
    price: 5,
    isAtive: true,
    bestSellers: false,
  ),
  Coffee(
    name: 'Macchiato 5',
    intensity: 4,
    beverageType: 'Macchiato',
    price: 4.90,
    isAtive: true,
    bestSellers: false,
  ),
];
