class Coffee {
  Coffee({
    required this.name,
    required this.intensity,
    required this.beverageType,
    required this.price,
    required this.isAtive,
    required this.bestSellers,
    required this.imageAssets,
  });
  final String name;
  final int intensity;
  final String beverageType;
  final double price;
  final bool isAtive;
  final bool bestSellers;
  final String imageAssets;
}

List<Coffee> coffees = [
  Coffee(
    name: 'Espresso Intenso',
    intensity: 9,
    beverageType: 'Espresso',
    price: 3.50,
    isAtive: true,
    bestSellers: true,
    imageAssets: 'assets/images/espresso1.jpg',
  ),
  Coffee(
    name: 'Espresso Gelado',
    intensity: 7,
    beverageType: 'Espresso',
    price: 4,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/espresso2.jpg',
  ),
  Coffee(
    name: 'Espresso',
    intensity: 7,
    beverageType: 'Espresso',
    price: 3.75,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/espresso3.jpg',
  ),
  Coffee(
    name: 'Espresso Barista',
    intensity: 6,
    beverageType: 'Espresso',
    price: 3.90,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/espresso4.jpg',
  ),
  Coffee(
    name: 'Cappuccino',
    intensity: 3,
    beverageType: 'Cappuccino',
    price: 5.50,
    isAtive: true,
    bestSellers: true,
    imageAssets: 'assets/images/cappuccino1.jpg',
  ),
  Coffee(
    name: 'Cappuccino Doce de Leite',
    intensity: 4,
    beverageType: 'Cappuccino',
    price: 6,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/cappuccino2.jpg',
  ),
  Coffee(
    name: 'Cappuccino Gelado',
    intensity: 3,
    beverageType: 'Cappuccino',
    price: 5.75,
    isAtive: true,
    bestSellers: true,
    imageAssets: 'assets/images/cappuccino3.jpg',
  ),
  Coffee(
    name: 'Cappuccino Zero Lactose',
    intensity: 4,
    beverageType: 'Cappuccino',
    price: 6.20,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/cappuccino4.jpg',
  ),
  Coffee(
    name: 'Cappuccino Vanilla',
    intensity: 3,
    beverageType: 'Cappuccino',
    price: 5.90,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/cappuccino5.jpg',
  ),
  Coffee(
    name: 'Latte Avelã',
    intensity: 3,
    beverageType: 'Latte',
    price: 6,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/latte1.jpg',
  ),
  Coffee(
    name: 'Latte Macchiato',
    intensity: 3,
    beverageType: 'Latte',
    price: 6.25,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/latte2.jpg',
  ),
  Coffee(
    name: 'Frappe Gelado',
    intensity: 2,
    beverageType: 'Latte',
    price: 5.75,
    isAtive: true,
    bestSellers: true,
    imageAssets: 'assets/images/latte3.jpg',
  ),
  Coffee(
    name: 'Frappe',
    intensity: 3,
    beverageType: 'Latte',
    price: 6.50,
    isAtive: true,
    bestSellers: true,
    imageAssets: 'assets/images/latte4.jpg',
  ),
  Coffee(
    name: 'Mocha',
    intensity: 4,
    beverageType: 'Mocha',
    price: 4.50,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/mocha1.jpg',
  ),
  Coffee(
    name: 'Chococino',
    intensity: 3,
    beverageType: 'Mocha',
    price: 4.75,
    isAtive: true,
    bestSellers: true,
    imageAssets: 'assets/images/mocha2.jpg',
  ),
  Coffee(
    name: 'Chococino Caramel',
    intensity: 4,
    beverageType: 'Mocha',
    price: 4.60,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/mocha3.jpg',
  ),
  Coffee(
    name: 'Mocha Gelado',
    intensity: 3,
    beverageType: 'Mocha',
    price: 5,
    isAtive: true,
    bestSellers: false,
    imageAssets: 'assets/images/mocha4.jpg',
  ),
];
